In [59]:
import pandas as pd
import numpy as np
from datetime import datetime

In [60]:
dataset = pd.read_csv('./data/dataset.csv')
dataset.columns

/var/folders/hj/jvkrj0mn5h76l2yb72psfp9c0000gn/T/ipykernel_61422/4293199037.py:1: DtypeWarning: Columns (17) have mixed types. Specify dtype option on import or set low_memory=False.
  dataset = pd.read_csv('./data/dataset.csv')

Index(['Unnamed: 0', 'raceId', 'year', 'round', 'circuitId', 'name', 'date',
       'time', 'circuit_id', 'weather_warm', 'weather_cold', 'weather_dry',
       'weather_wet', 'weather_cloudy', 'resultId', 'driverId',
       'constructorId', 'car_number', 'grid', 'results_positionOrder',
       'results_points', 'laps', 'milliseconds', 'fastestLap',
       'fastestLapTime', 'fastestLapSpeed', 'statusId', 'status',
       'circuit_location', 'country', 'constructorStandingsId',
       'constructor_points', 'constructor_position', 'constructor_wins',
       'constructorRef', 'constructor_nationality', 'driverRef',
       'driver_number', 'driver_code', 'forename', 'dob', 'driver_nationality',
       'driverStandingsId', 'driver_points', 'driver_position', 'driver_wins',
       'qualifyId', 'number', 'qualifying_position', 'q1_time', 'q2_time',
       'q3_time', 'no_of_stops', 'ms_avg', 'first_5_avg_time',
       'last_10_avg_time', 'lap_position_after_5',
       'lap_position_before_last_10'],
      dtype='object')

In [61]:
dataset.shape[0]

25660

In [62]:
sprint_results = pd.read_csv('./data/sprint_results.csv')
sprint_results.columns

Index(['resultId', 'raceId', 'driverId', 'constructorId', 'number', 'grid',
       'position', 'positionText', 'positionOrder', 'points', 'laps', 'time',
       'milliseconds', 'fastestLap', 'fastestLapTime', 'statusId'],
      dtype='object')

In [63]:
sprint_results

,resultId,raceId,driverId,constructorId,number,grid,position,positionText,positionOrder,points,laps,time,milliseconds,fastestLap,fastestLapTime,statusId
0,1,1061,830,9,33,2,1,1,1,3,17,25:38.426,1538426,14,1:30.013,1
1,2,1061,1,131,44,1,2,2,2,2,17,+1.430,1539856,17,1:29.937,1
2,3,1061,822,131,77,3,3,3,3,1,17,+7.502,1545928,17,1:29.958,1
3,4,1061,844,6,16,4,4,4,4,0,17,+11.278,1549704,16,1:30.163,1
4,5,1061,846,1,4,6,5,5,5,0,17,+24.111,1562537,16,1:30.566,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,96,1084,848,3,23,11,16,16,16,0,23,+52.412,1642471,5,1:10.367,1
96,97,1084,852,213,22,14,17,17,17,0,23,+54.556,1644615,4,1:10.267,1
97,98,1084,849,3,6,19,18,18,18,0,23,+1:08.694,1658753,4,1:10.284,1
98,99,1084,20,117,5,20,19,19,19,0,21,\N,\N,4,1:10.317,130
99,100,1084,4,214,14,8,\N,N,20,0,0,\N,\N,\N,\N,10

In [64]:
sprint_results.shape[0]

100

In [65]:
qualifier_columns = dataset[['raceId', 'year', 'circuitId', 'driverId', 'constructorId', 'qualifyId', 'qualifying_position', 'q1_time', 'q2_time', 'q3_time']]
qualifier_columns

,raceId,year,circuitId,driverId,constructorId,qualifyId,qualifying_position,q1_time,q2_time,q3_time
0,1,2009,1,18,23,2986.0,1.0,1:25.211,1:24.855,1:26.202
1,90,2004,1,18,16,4084.0,4.0,1:24.998,\N,\N
2,108,2003,1,18,16,3789.0,8.0,1:28.682,\N,\N
3,338,2010,1,18,1,3353.0,4.0,1:24.897,1:24.531,1:24.675
4,841,2011,1,18,1,4540.0,4.0,1:25.886,1:24.957,1:24.779
...,...,...,...,...,...,...,...,...,...,...
25655,815,1953,66,720,6,NaN,NaN,NaN,NaN,NaN
25656,817,1952,66,720,141,NaN,NaN,NaN,NaN,NaN
25657,815,1953,66,719,133,NaN,NaN,NaN,NaN,NaN
25658,832,1951,67,783,154,NaN,NaN,NaN,NaN,NaN
25659,832,1951,67,782,105,NaN,NaN,NaN,NaN,NaN

In [66]:
new_qualifier_columns = qualifier_columns.dropna(axis=0, subset=['qualifying_position'])
sorted_qualifier_columns = new_qualifier_columns.sort_values(by=['raceId'], ascending=True)
sorted_qualifier_columns

,raceId,year,circuitId,driverId,constructorId,qualifyId,qualifying_position,q1_time,q2_time,q3_time
0,1,2009,1,18,23,2986.0,1.0,1:25.211,1:24.855,1:26.202
2591,1,2009,1,8,6,2994.0,9.0,1:25.899,1:25.380,1:27.163
8842,1,2009,1,6,3,2998.0,13.0,1:26.074,1:25.607,\N
2469,1,2009,1,5,1,2999.0,14.0,1:26.184,1:25.726,\N
2178,1,2009,1,1,1,3000.0,15.0,1:26.454,\N,\N
...,...,...,...,...,...,...,...,...,...,...
8046,1086,2022,11,830,9,9442.0,10.0,1:18.509,1:17.703,1:18.823
10054,1086,2022,11,849,3,9452.0,20.0,1:19.570,\N,\N
7887,1086,2022,11,832,6,9434.0,2.0,1:18.434,1:17.946,1:17.421
2293,1086,2022,11,1,131,9439.0,7.0,1:18.374,1:18.035,1:18.142
8456,1086,2022,11,840,117,9446.0,14.0,1:19.205,1:19.137,\N

In [67]:
sprints_match2021 = sorted_qualifier_columns.loc[sorted_qualifier_columns['year'] == 2021]
sprints_match2021

,raceId,year,circuitId,driverId,constructorId,qualifyId,qualifying_position,q1_time,q2_time,q3_time
8528,1051,2021,78,840,117,9127.0,12.0,1:22.551,1:22.460,\N
8140,1051,2021,78,830,9,9117.0,2.0,1:21.996,1:21.984,1:21.282
10032,1051,2021,78,852,213,9123.0,8.0,1:22.458,1:22.058,1:21.881
2463,1051,2021,78,1,131,9116.0,1.0,1:21.901,1:21.682,1:20.827
8415,1051,2021,78,844,6,9128.0,13.0,1:22.742,1:22.463,\N
...,...,...,...,...,...,...,...,...,...,...
9939,1073,2021,24,841,51,9169.0,14.0,1:24.118,1:24.251,\N
10062,1073,2021,24,849,3,9171.0,16.0,1:24.338,\N,\N
6205,1073,2021,24,20,117,9170.0,15.0,1:24.225,1:24.305,\N
8376,1073,2021,24,844,6,9162.0,7.0,1:23.467,1:23.202,1:23.122
8731,1073,2021,24,842,213,9167.0,12.0,1:23.489,1:24.043,\N

In [68]:
sprints2021 = sprint_results.loc[(sprint_results['raceId'] >= 1051) & (sprint_results['raceId'] <= 1073)]
sprints2021

,resultId,raceId,driverId,constructorId,number,grid,position,positionText,positionOrder,points,laps,time,milliseconds,fastestLap,fastestLapTime,statusId
0,1,1061,830,9,33,2,1,1,1,3,17,25:38.426,1538426,14,1:30.013,1
1,2,1061,1,131,44,1,2,2,2,2,17,+1.430,1539856,17,1:29.937,1
2,3,1061,822,131,77,3,3,3,3,1,17,+7.502,1545928,17,1:29.958,1
3,4,1061,844,6,16,4,4,4,4,0,17,+11.278,1549704,16,1:30.163,1
4,5,1061,846,1,4,6,5,5,5,0,17,+24.111,1562537,16,1:30.566,1
5,6,1061,817,1,3,7,6,6,6,0,17,+30.959,1569385,17,1:30.640,1
6,7,1061,4,214,14,11,7,7,7,0,17,+43.527,1581953,17,1:31.773,1
7,8,1061,20,117,5,10,8,8,8,0,17,+44.439,1582865,17,1:31.687,1
8,9,1061,847,3,63,8,9,9,9,0,17,+46.652,1585078,17,1:32.208,1
9,10,1061,839,214,31,13,10,10,10,0,17,+47.395,1585821,16,1:32.183,1
10,11,1061,832,6,55,9,11,11,11,0,17,+47.798,1586224,10,1:31.991,1
11,12,1061,842,213,10,12,12,12,12,0,17,+48.763,1587189,17,1:32.072,1
12,13,1061,8,51,7,17,13,13,13,0,17,+50.677,1589103,12,1:32.139,1
13,14,1061,840,117,18,15,14,14,14,0,17,+52.179,1590605,12,1:32.210,1
14,15,1061,841,51,99,14,15,15,15,0,17,+53.225,1591651,14,1:32.457,1
15,16,1061,852,213,22,16,16,16,16,0,17,+53.567,1591993,14,1:32.270,1
16,17,1061,849,3,6,18,17,17,17,0,17,+55.162,1593588,17,1:32.143,1
17,18,1061,854,210,47,19,18,18,18,0,17,+1:08.213,1606639,15,1:32.567,1
18,19,1061,853,210,9,20,19,19,19,0,17,+1:17.648,1616074,3,1:33.462,1
19,20,1061,815,9,11,5,\N,R,20,0,16,\N,\N,6,1:31.465,76
20,21,1065,822,131,77,1,1,1,1,3,18,27:54.078,1674078,9,1:23.540,1
21,22,1065,830,9,33,3,2,2,2,2,18,+2.325,1676403,9,1:23.502,1
22,23,1065,817,1,3,5,3,3,3,1,18,+14.534,1688612,17,1:24.291,1
23,24,1065,846,1,4,4,4,4,4,0,18,+18.835,1692913,9,1:24.554,1
24,25,1065,1,131,44,2,5,5,5,0,18,+20.011,1694089,9,1:24.253,1
25,26,1065,844,6,16,8,6,6,6,0,18,+23.442,1697520,18,1:24.677,1
26,27,1065,832,6,55,7,7,7,7,0,18,+27.952,1702030,8,1:24.918,1
27,28,1065,841,51,99,10,8,8,8,0,18,+31.089,1705167,10,1:25.126,1
28,29,1065,815,9,11,9,9,9,9,0,18,+31.680,1705758,12,1:24.211,1
29,30,1065,840,117,18,12,10,10,10,0,18,+38.671,1712749,8,1:25.349,1
30,31,1065,4,214,14,13,11,11,11,0,18,+39.795,1713873,8,1:25.225,1
31,32,1065,20,117,5,11,12,12,12,0,18,+41.177,1715255,8,1:25.493,1
32,33,1065,839,214,31,14,13,13,13,0,18,+43.373,1717451,8,1:25.613,1
33,34,1065,849,3,6,16,14,14,14,0,18,+45.977,1720055,9,1:25.711,1
34,35,1065,847,3,63,15,15,15,15,0,18,+46.821,1720899,15,1:25.835,1
35,36,1065,852,213,22,17,16,16,16,0,18,+49.977,1724055,18,1:25.847,1
36,37,1065,853,210,9,20,17,17,17,0,18,+1:02.599,1736677,7,1:26.613,1
37,38,1065,9,51,88,19,18,18,18,0,18,+1:05.096,1739174,12,1:26.772,1
38,39,1065,854,210,47,18,19,19,19,0,18,+1:06.154,1740232,7,1:26.819,1
39,40,1065,842,213,10,6,\N,R,20,0,0,\N,\N,\N,\N,3
40,41,1071,822,131,77,2,1,1,1,3,24,29:09.559,1749559,8,1:12.300,1
41,42,1071,830,9,33,1,2,2,2,2,24,+1.170,1750729,9,1:12.114,1
42,43,1071,832,6,55,5,3,3,3,1,24,+18.723,1768282,13,1:13.167,1
43,44,1071,815,9,11,3,4,4,4,0,24,+19.787,1769346,13,1:13.110,1
44,45,1071,1,131,44,20,5,5,5,0,24,+20.872,1770431,5,1:12.357,1
45,46,1071,846,1,4,7,6,6,6,0,24,+22.558,1772117,8,1:12.994,1
46,47,1071,844,6,16,6,7,7,7,0,24,+25.056,1774615,4,1:13.140,1
47,48,1071,842,213,10,4,8,8,8,0,24,+34.158,1783717,4,1:13.342,1
48,49,1071,839,214,31,10,9,9,9,0,24,+34.632,1784191,11,1:13.615,1
49,50,1071,20,117,5,11,10,10,10,0,24,+34.867,1784426,5,1:13.558,1
50,51,1071,817,1,3,8,11,11,11,0,24,+35.869,1785428,9,1:13.463,1
51,52,1071,4,214,14,9,12,12,12,0,24,+36.578,1786137,4,1:13.397,1
52,53,1071,841,51,99,14,13,13,13,0,24,+41.880,1791439,11,1:13.627,1
53,54,1071,840,117,18,15,14,14,14,0,24,+44.037,1793596,9,1:13.666,1
54,55,1071,852,213,22,12,15,15,15,0,24,+46.150,1795709,11,1:13.747,1
55,56,1071,849,3,6,16,16,16,16,0,24,+46.760,1796319,7,1:13.934,1
56,57,1071,847,3,63,17,17,17,17,0,24,+47.739,1797298,14,1:14.056,1
57,58,1071,8,51,7,13,18,18,18,0,24,+50.014,1799573,9,1:13.900,1
58,59,1071,854,210,47,18,19,19,19,0,24,+1:01.680,1811239,9,1:14.387,1
59,60,1071,853,210,9,19,20,20,20,0,24,+1:07.474,1817033,6,1:14.583,1

In [69]:
sprints_match2022 = sorted_qualifier_columns.loc[sorted_qualifier_columns['year'] == 2022]
sprints_match2022

,raceId,year,circuitId,driverId,constructorId,qualifyId,qualifying_position,q1_time,q2_time,q3_time
8428,1074,2022,3,840,117,9194.0,19.0,1:33.032,\N,\N
7530,1074,2022,3,807,117,9192.0,17.0,1:32.777,\N,\N
8233,1074,2022,3,839,214,9186.0,11.0,1:32.041,1:31.782,\N
6463,1074,2022,3,815,9,9179.0,4.0,1:32.311,1:31.008,1:30.921
7336,1074,2022,3,822,51,9181.0,6.0,1:31.919,1:31.717,1:31.560
...,...,...,...,...,...,...,...,...,...,...
8046,1086,2022,11,830,9,9442.0,10.0,1:18.509,1:17.703,1:18.823
10054,1086,2022,11,849,3,9452.0,20.0,1:19.570,\N,\N
7887,1086,2022,11,832,6,9434.0,2.0,1:18.434,1:17.946,1:17.421
2293,1086,2022,11,1,131,9439.0,7.0,1:18.374,1:18.035,1:18.142
8456,1086,2022,11,840,117,9446.0,14.0,1:19.205,1:19.137,\N

In [70]:
sprints2022 = sprint_results.loc[(sprint_results['raceId'] >= 1074) & (sprint_results['raceId'] <= 1086)]
sprints2022

,resultId,raceId,driverId,constructorId,number,grid,position,positionText,positionOrder,points,laps,time,milliseconds,fastestLap,fastestLapTime,statusId
60,61,1077,830,9,1,1,1,1,1,8,21,30:39.567,1839567,14,1:19.154,1
61,62,1077,844,6,16,2,2,2,2,7,21,+2.975,1842542,11,1:19.044,1
62,63,1077,815,9,11,7,3,3,3,6,21,+4.721,1844288,14,1:19.012,1
63,64,1077,832,6,55,10,4,4,4,5,21,+17.578,1857145,14,1:19.251,1
64,65,1077,846,1,4,3,5,5,5,4,21,+24.561,1864128,9,1:20.030,1
65,66,1077,817,1,3,6,6,6,6,3,21,+27.740,1867307,12,1:20.328,1
66,67,1077,822,51,77,8,7,7,7,2,21,+28.133,1867700,9,1:20.219,1
67,68,1077,825,210,20,4,8,8,8,1,21,+30.712,1870279,6,1:20.557,1
68,69,1077,4,214,14,5,9,9,9,0,21,+32.278,1871845,10,1:20.639,1
69,70,1077,854,210,47,12,10,10,10,0,21,+33.773,1873340,15,1:20.567,1
70,71,1077,847,131,63,11,11,11,11,0,21,+36.284,1875851,19,1:20.756,1
71,72,1077,852,213,22,16,12,12,12,0,21,+38.298,1877865,20,1:20.909,1
72,73,1077,20,117,5,9,13,13,13,0,21,+40.177,1879744,8,1:21.044,1
73,74,1077,1,131,44,13,14,14,14,0,21,+41.459,1881026,9,1:20.663,1
74,75,1077,840,117,18,15,15,15,15,0,21,+42.910,1882477,14,1:20.948,1
75,76,1077,839,214,31,19,16,16,16,0,21,+43.517,1883084,14,1:20.995,1
76,77,1077,842,213,10,17,17,17,17,0,21,+43.794,1883361,18,1:20.599,1
77,78,1077,848,3,23,20,18,18,18,0,21,+48.871,1888438,14,1:21.020,1
78,79,1077,849,3,6,18,19,19,19,0,21,+52.017,1891584,16,1:21.437,1
79,80,1077,855,51,24,0,\N,R,20,0,0,\N,\N,\N,\N,31
80,81,1084,830,9,1,1,1,1,1,8,23,26:30.059,1590059,5,1:08.455,1
81,82,1084,844,6,16,2,2,2,2,7,23,+1.675,1591734,4,1:08.321,1
82,83,1084,832,6,55,3,3,3,3,6,23,+5.644,1595703,4,1:08.409,1
83,84,1084,847,131,63,4,4,4,4,5,23,+13.429,1603488,4,1:08.979,1
84,85,1084,815,9,11,13,5,5,5,4,23,+18.302,1608361,14,1:09.137,1
85,86,1084,839,214,31,5,6,6,6,3,23,+31.032,1621091,4,1:09.384,1
86,87,1084,825,210,20,6,7,7,7,2,23,+34.539,1624598,4,1:09.232,1
87,88,1084,1,131,44,9,8,8,8,1,23,+35.447,1625506,7,1:09.516,1
88,89,1084,854,210,47,7,9,9,9,0,23,+37.163,1627222,4,1:09.457,1
89,90,1084,822,51,77,12,10,10,10,0,23,+37.557,1627616,4,1:09.674,1
90,91,1084,846,1,4,15,11,11,11,0,23,+38.580,1628639,8,1:09.909,1
91,92,1084,817,1,3,16,12,12,12,0,23,+39.738,1629797,8,1:09.996,1
92,93,1084,840,117,18,17,13,13,13,0,23,+48.241,1638300,4,1:10.295,1
93,94,1084,855,51,24,18,14,14,14,0,23,+50.753,1640812,11,1:10.165,1
94,95,1084,842,213,10,10,15,15,15,0,23,+52.125,1642184,4,1:10.409,1
95,96,1084,848,3,23,11,16,16,16,0,23,+52.412,1642471,5,1:10.367,1
96,97,1084,852,213,22,14,17,17,17,0,23,+54.556,1644615,4,1:10.267,1
97,98,1084,849,3,6,19,18,18,18,0,23,+1:08.694,1658753,4,1:10.284,1
98,99,1084,20,117,5,20,19,19,19,0,21,\N,\N,4,1:10.317,130
99,100,1084,4,214,14,8,\N,N,20,0,0,\N,\N,\N,\N,10

In [71]:
print(sprints2022["raceId"].unique())
print(sprints_match2022["raceId"].unique())

[1077 1084]
[1074 1075 1076 1077 1078 1079 1080 1081 1082 1083 1084 1085 1086]

In [72]:
print(sprints2021["raceId"].unique())
print(sprints_match2021["raceId"].unique())

[1061 1065 1071]
[1051 1052 1053 1054 1055 1056 1057 1058 1059 1060 1061 1062 1063 1064
 1065 1066 1067 1069 1070 1071 1072 1073]

Result: Not taking sprints into account at all since data is extremely less

In [73]:
q1_time_df = sorted_qualifier_columns['q1_time']
q2_time_df = sorted_qualifier_columns['q2_time']
q3_time_df = sorted_qualifier_columns['q3_time']

sorted_qualifier_columns.drop(['q1_time', 'q2_time', 'q3_time', 'qualifyId'], axis=1, inplace=True)

In [74]:
q1_time_ms = []
q2_time_ms = []
q3_time_ms = []

for i in q1_time_df:
    if(i != '\\N' and i==i):
        x = datetime.strptime(i,'%M:%S.%f')
        q1_time_ms.append((x.minute*60*100) + (x.second*100) + (x.microsecond/1000))
    else:
        q1_time_ms.append(0)

for i in q2_time_df:
    if(i != '\\N' and i==i):
        x = datetime.strptime(i,'%M:%S.%f')
        q2_time_ms.append((x.minute*60*100) + (x.second*100) + (x.microsecond/1000))
    else:
        q2_time_ms.append(0)

for i in q3_time_df:
    if(i != '\\N' and i==i):
        x = datetime.strptime(i,'%M:%S.%f')
        q3_time_ms.append((x.minute*60*100) + (x.second*100) + (x.microsecond/1000))
    else:
        q3_time_ms.append(0)

q1_time_ms = pd.Series(q1_time_ms)
q2_time_ms = pd.Series(q2_time_ms)
q3_time_ms = pd.Series(q3_time_ms)

In [75]:
q1_time_max = q1_time_ms.max()
q2_time_max = q2_time_ms.max()
q3_time_max = q3_time_ms.max()

q1_time_ms = q1_time_ms.replace(0, q1_time_max*2)
q2_time_ms = q2_time_ms.replace(0, q2_time_max*2)
q3_time_ms = q3_time_ms.replace(0, q3_time_max*2)

temp_qualifier1 = pd.concat((sorted_qualifier_columns.reset_index(drop=True), q1_time_ms.rename('q1_time_ms').reset_index(drop=True)), axis=1)
temp_qualifier2 = pd.concat((temp_qualifier1, q2_time_ms.rename('q2_time_ms')), axis=1)
temp_qualifier3 = pd.concat((temp_qualifier2, q3_time_ms.rename('q3_time_ms')), axis=1)
temp_qualifier3

,raceId,year,circuitId,driverId,constructorId,qualifying_position,q1_time_ms,q2_time_ms,q3_time_ms
0,1,2009,1,18,23,1.0,8711.0,9255.0,8802.0
1,1,2009,1,8,6,9.0,9399.0,8880.0,8863.0
2,1,2009,1,6,3,13.0,8674.0,9107.0,27352.0
3,1,2009,1,5,1,14.0,8784.0,9226.0,27352.0
4,1,2009,1,1,1,15.0,9054.0,27578.0,27352.0
...,...,...,...,...,...,...,...,...,...
9380,1086,2022,11,830,9,10.0,8309.0,8403.0,8623.0
9381,1086,2022,11,849,3,20.0,8470.0,27578.0,27352.0
9382,1086,2022,11,832,6,2.0,8234.0,8646.0,8121.0
9383,1086,2022,11,1,131,7.0,8174.0,7835.0,7942.0
9384,1086,2022,11,840,117,14.0,8105.0,8037.0,27352.0

In [90]:
temp_qualifier3.to_csv('./qualifier_data/qualify.csv')

In [91]:
temp_qualifier3.columns

Index(['raceId', 'year', 'circuitId', 'driverId', 'constructorId',
       'qualifying_position', 'q1_time_ms', 'q2_time_ms', 'q3_time_ms'],
      dtype='object')